stages:
  - test
  
variables:
  REPO_NAME: ${{ github.event.repository.name }}

test:
  stage: test
  image: alpine
  script:
    - apk add curl
    - curl https://$GITHUB_REPOSITORY_OWNER.github.io/REPO_NAME grep -q "CICD"
